### ISSUE TITLE
Comment Format Not Working With angular-ui-router Resolves, Worked With Regular ng-annotate

### ISSUE THREAD

**Issue by trisys3** [schmod/babel-plugin-angularjs-annotate#26] opened 2017-07-10 15:44 UTC
Comments are allowed on actual providers (`.provider`, `.factory`, `.controller`, etc.), but not on `UI Router` resolves. On the previous, now-deprecated `ng-annotate`, comments are allowed here, too. This is easily worked around, as we can use the directive form (`'ngInject';` as the first statement in a resolve), but it could cause major headaches during transition from `ng-annotate` to `babel-plugin-angularjs-annotate`, which is already bad enough with having to add `babel` to the build process.

For example,

```
angular.module('myApp', myState);

/** @ngInject */
function myState($stateRegistry) {
    $stateRegistry.register({
        name: 'myState',
        url: '/',
        resolve: {
            /** @ngInject */
            myResolve: function($state) {
            },
        },
    });
}
```

worked with `ng-annotate`, but not with this plugin. With this plugin, it throws an error saying "The transition errored", with a type of 6. If you need any more information, I can find it, but I am not sure what kind is generally useful.

On the other hand,

```
angular.module('myApp', myState);

/** @ngInject */
function myState($stateRegistry) {
    $stateRegistry.register({
        name: 'myState',
        url: '/',
        resolve: {
            myResolve: function($state) {
                'ngInject';
            },
        },
    });
}
```

still works.

For others looking at this issue, it is also worth noting that resolves without any dependencies will still work with the comment format. Also, this will not break your app, just that one state.

**Comment by schmod** [comment] 2017-07-12 15:38
This looks like a duplicate of #23, because you're using a double-asterisk in your comment.

**Closed** 2017-07-12 15:38 UTC
Labels: duplicate

**Comment by schmod** [comment] 2017-07-12 15:41
fixed in 0.8.0

**Comment by trisys3** [comment] 2017-07-12 15:55
Thanks, I'll check. It's weird that double-asterisk worked other places.

**Comment by trisys3** [comment] 2017-07-12 16:08
Just checked, everything looks fine. Thanks for the quick turnaround!
